### ISSUE TITLE
init.sh is out of date.  docker-compose no longer exists.  Users can't install snikket self hosted

### ISSUE THREAD

**Issue by therealrobster** [snikket-im/snikket-selfhosted#14]
Hi all,

Your self hosted script is broken, and nobody can use it.

`docker compose` is the new way to use docker, and the script still has `docker-compose`.  This breaks install.

```
root@chat:~# cd /opt/snikket/
root@chat:/opt/snikket# ./scripts/init.sh
Docker Compose (docker-compose) is required but not installed.
Please follow the installation guide at https://docs.docker.com/compose/install/
root@chat:/opt/snikket# 

```

I hope that helps.

**Comment by mwild1** [comment]
Hi! Thanks for the feedback. Thankfully plenty of people have been installing Snikket self-hosted daily - these scripts are rarely used, as most people follow the [setup guide](https://snikket.org/quickstart) which is linked on the website.

But you're right, Compose V1 has been deprecated a while (though it's still surprising how many servers still have it!), and switching to V2 is the correct thing to do. I've updated the scripts and docs accordingly.

If you see anything else amiss, let me know!
