### ISSUE TITLE
firewall settings

### ISSUE THREAD

**Issue by g33kdad** [snikket-im/snikket-selfhosted#6]
Hi,
I have been trying to set up snikket with docker using the quick-start guide. I chose AlmaLinux 8 as my base os. AlmaLinux uses firewalld and there are no instructions for what services/ports are required to be let through the firewall.

What ports are required?

**Comment by iamarya2k24** [comment]
@g33kdad kindly check this document for info on firewall.
https://github.com/snikket-im/snikket-server/blob/master/docs/advanced/firewall.md
