### ISSUE TITLE
Why Docker?

### ISSUE THREAD

**Issue by tuaris** [snikket-im/snikket-selfhosted#9]
You write a wonderful article with excellent points (https://snikket.org/blog/products-vs-protocols/) and (I quote) "The goal is to reduce fragmentation in the XMPP ecosystem, and ensure that people have access to a familiar brand across all platforms.".  Yet you are using Docker for your self-hosted setup without any documentation on how to not use Docker, which limits the platforms to just Linux.  Any chance we can get instructions on how to deploy without Docker?

**Comment by tuaris** [comment]
Well, at least it looks like you are using Ansible for provisioning the software stack.

**Comment by mwild1** [comment]
Hi, thanks for the question. The question of why we use Docker is answered in the FAQ on the main site here: https://snikket.org/faq/#q-can-i-set-up-snikket-without-docker

Hope this helps!
